name: CI

on:
  push:
    branches: [master]

jobs:
  test-and-generate-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.1
        with:
          version: 6.32.1
      - run: pnpm install
      - run: pnpm ci:test
      - name: Generate README.
        run: node ./.github/generate-readme.js
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: update"
          file_pattern: README.md
