name: CI

on:
  push:
    branches: [master]

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate README.
        run: node ./.github/readme-generate.js
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: update"
          file_pattern: README.md
